// resources/js/poc/solid/mount.jsx
import { render } from 'solid-js/web';
import { AMLForm } from './AMLForm.jsx';

/**
 * Mount the Solid renderer into a wire:ignore host.
 *
 * @param {Element} host
 * @param {import('wire-bridge').WireBridge} bridge
 * @returns {{ destroy: () => void }}
 */
export function mount(host, bridge) {
    const dispose = render(() => <AMLForm bridge={bridge} />, host);

    return {
        destroy: dispose,
    };
}

// resources/js/order/react/mount.jsx
/** @jsxImportSource react */
import { createRoot } from 'react-dom/client';
import { LineItems } from './LineItems.jsx';

/**
 * @param {Element} host
 * @param {import('wire-bridge').WireBridge} bridge
 * @returns {{ destroy: () => void }}
 */
export function mount(host, bridge) {
    const root = createRoot(host);

    root.render(<LineItems bridge={bridge} />);

    return {
        destroy: () => queueMicrotask(() => root.unmount()),
    };
}
